name: CI/CD mpmt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # --------------------------
  # 🧪 1. FRONTEND TEST & BUILD
  # --------------------------
  frontend:
    name: Frontend - Test & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test -- --no-watch --browsers=ChromeHeadless

      - name: Build Angular app
        run: npm run build

  # --------------------------
  # ☕ 2. BACKEND BUILD
  # --------------------------
  backend:
    name: Backend - Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mpmt
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Test backend
        run: mvn clean verify -DskipTests

  # --------------------------
  # 🐳 3. PUSH DOCKERHUB IMAGES
  # --------------------------
  docker:
    name: DockerHub Push
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FRONTEND image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mpmt-client:latest,${{ secrets.DOCKERHUB_USERNAME }}/mpmt-client:${{ github.sha }}

      - name: Build and push BACKEND image
        uses: docker/build-push-action@v5
        with:
          context: ./mpmt
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mpmt-server:latest,${{ secrets.DOCKERHUB_USERNAME }}/mpmt-server:${{ github.sha }}